backend:
  title: 后台菜单
  groups:
    - title: 栏目管理
      children:
        - title: 栏目分类
          route: /channel/index
          permission: channel.channel.manage
        - title: 数据列表
          route: /channel_model/index
          permission: channel.content.manage
        - title: 内容回收站
          route: /recycle_bin/index
          permission: channel.recycle_bin.manage
    - title: 管理员管理
      children:
        - title: 管理员列表
          route: /admin/index
          permission: admin.admin.manage
        - title: 角色列表
          route: /role/index
          permission: admin.role.manage
    - title: 系统设置
      children:
        - title: 快捷方式
          route: /quick/index
          permission: setting.quick.manage
        - title: 友情链接
          route: /link/index
          permission: setting.link.manage
        - title: 站点配置
          route: /setting/index
          permission: setting.setting.manage

backend_api:
  title: 后台接口
  groups:
    - title: 栏目管理
      children:
        - title: 栏目分类列表
          route: /channel/index
          permission: channel.channel.index
        - title: 栏目启用禁用
          route: /channel/status
          permission: channel.channel.status
        - title: 栏目删除
          route: /channel/delete
          permission: channel.channel.delete
        - title: 栏目添加
          route: /channel/add
          permission: channel.channel.add
        - title: 栏目编辑
          route: /channel/edit
          permission: channel.channel.edit
    - title: 管理员管理
      children:
        - title: 管理员新增
          route: /admin/add
          permission: admin.admin.add
        - title: 管理员编辑
          route: /admin/edit
          permission: admin.admin.edit
        - title: 管理员启用/停用
          route: /admin/status
          permission: admin.admin.status
        - title: 管理员删除
          route: /admin/delete
          permission: admin.admin.delete
        - title: 管理员批量删除
          route: /admin/delete_batch
          permission: admin.admin.delete_batch
        - title: 角色新增
          route: /role/add
          permission: admin.role.add
        - title: 角色编辑
          route: /role/edit
          permission: admin.role.edit
        - title: 角色启用/停用
          route: /role/status
          permission: admin.role.status
        - title: 角色删除
          route: /role/delete
          permission: admin.role.delete
        - title: 角色批量删除
          route: /role/delete_batch
          permission: admin.role.delete_batch
    - title: 系统设置
      children:
        - title: 保存配置
          route: /setting/save
          permission: setting.setting.save