backend:
  title: 后台菜单
  groups:
    - title: 栏目管理
      children:
        - title: 栏目分类
          route: /channel/index
          permission: channel.channel.manage
        - title: 数据列表
          route: /channel_model/index
          permission: channel.channel.manage
        - title: 内容回收站
          route: /recycle_bin/index
          permission: channel.recycle_bin.manage
    - title: 管理员管理
      children:
        - title: 管理员列表
          route: /admin/index
          permission: admin.admin.manage
        - title: 角色列表
          route: /role/index
          permission: admin.role.manage
    - title: 系统设置
      children:
        - title: 快捷方式
          route: /quick/index
          permission: setting.quick.manage
        - title: 友情链接
          route: /link/index
          permission: setting.link.manage
        - title: 站点配置
          route: /setting/index
          permission: setting.setting.manage

backend_api:
  title: 后台接口
  groups:
    - title: 系统设置
      children:
        - title: 保存配置
          route: /setting/save
          permission: setting.setting.save