backend_view:
  title: 后台权限
  groups:
    - title: 栏目管理
      slug: channel
      permissions:
        - title: 栏目分类
          slug: channel.manage
        - title: 数据列表
          slug: content.manage
        - title: 内容回收站
          slug: recycle_bin.manage
    - title: 广告管理
      slug: ad
      permissions:
        - title: 广告分类
          slug: ad_channel.manage
        - title: 广告列表
          slug: ad_list.manage
    - title: 留言管理
      slug: guestbook
      permissions:
        - title: 留言列表
          slug: guestbook.manage
    - title: 管理员管理
      slug: admin
      permissions:
        - title: 管理员列表
          slug: admin.manage
        - title: 角色列表
          slug: role.manage
        - title: 权限分类
          slug: rule_channel.manage
        - title: 权限列表
          slug: rule.manage
    - title: 系统设置
      slug: setting
      permissions:
        - title: 快捷方式
          slug: shortcut.manage
        - title: 友情链接
          slug: friendly_link.manage
        - title: 站点配置
          slug: setting.manage
backend_api:
  title: 后台接口权限
  groups:
    - title: 栏目管理
      slug: channel
      permissions:
        - title: 栏目-分类列表
          slug: channel.index
        - title: 栏目-添加
          slug: channel.add
        - title: 栏目-编辑
          slug: channel.edit
        - title: 栏目-删除
          slug: channel.delete
        - title: 栏目-启用/禁用
          slug: channel.status
        - title: 文章-列表
          slug: article.index
        - title: 文章-添加
          slug: article.add
        - title: 文章-编辑
          slug: article.edit
        - title: 文章-删除
          slug: article.delete
        - title: 文章-排序
          slug: article.sort
        - title: 文章-flag(推荐、置顶)
          slug: article.flag
        - title: 文章-审核
          slug: article.status
        - title: 文章-移动
          slug: article.move
        - title: 图集-列表
          slug: image.index
        - title: 图集-添加
          slug: image.add
        - title: 图集-编辑
          slug: image.edit
        - title: 图集-删除
          slug: image.delete
        - title: 图集-排序
          slug: image.sort
        - title: 图集-flag(推荐、置顶)
          slug: image.flag
        - title: 图集-启用/停用
          slug: image.status
        - title: 图集-移动
          slug: image.move

        - title: 回收站-文章列表
          slug: recycle_bin.article_list
        - title: 回收站-文章批量永久删除
          slug: recycle_bin.article_batch_destroy
        - title: 回收站-文章批量恢复
          slug: recycle_bin.article_batch_restore
    - title: 广告管理
      slug: ad
      permissions:
        - title: 广告分类-列表
          slug: ad_channel.index
        - title: 广告分类-新增
          slug: ad_channel.add
        - title: 广告分类-编辑
          slug: ad_channel.edit
        - title: 广告分类-删除
          slug: ad_channel.delete
        - title: 广告分类-排序
          slug: ad_channel.sort
        - title: 广告-列表
          slug: ad_list.index
        - title: 广告-新增
          slug: ad_list.add
        - title: 广告-编辑
          slug: ad_list.edit
        - title: 广告-删除/批量删除
          slug: ad_list.delete
        - title: 广告-排序
          slug: ad_list.sort
        - title: 广告-批量启用/停用
          slug: ad_list.batch_status
    - title: 留言管理
      slug: guestbook
      permissions:
        - title: 修改状态
          slug: guestbook.status
        - title: 批量删除
          slug: guestbook.batch_delete
    - title: 管理员管理
      slug: admin
      permissions:
        - title: 管理员-新增
          slug: admin.add
        - title: 管理员-编辑
          slug: admin.edit
        - title: 管理员-启动/停用
          slug: admin.status
        - title: 管理员-删除
          slug: admin.delete
        - title: 管理员-批量删除
          slug: admin.delete_batch
        - title: 角色-新增
          slug: role.add
        - title: 角色-编辑
          slug: role.edit
        - title: 角色-启用/停用
          slug: role.status
        - title: 角色-删除
          slug: role.delete
        - title: 角色-批量删除
          slug: role.delete_batch
    - title: 系统设置
      slug: setting
      permissions:
        - title: 快捷方式-添加
          slug: shortcut.add
        - title: 快捷方式-编辑
          slug: shortcut.edit
        - title: 快捷方式-排序
          slug: shortcut.sort
        - title: 快捷方式-删除、批量删除
          slug: shortcut.batch_delete
        - title: 友情链接-添加
          slug: friendly_link.add
        - title: 友情链接-编辑
          slug: friendly_link.edit
        - title: 友情链接-排序
          slug: friendly_link.sort
        - title: 友情链接-删除、批量删除
          slug: friendly_link.batch_delete
        - title: 站点配置-保存
          slug: setting.save