backend:
  title: 后台权限
  groups:
    - title: 栏目管理
      slug: channel
      permissions:
        - title: 栏目分类
          slug: channel.manage
        - title: 档案列表
          slug: content.manage
        - title: 内容回收站
          slug: recycle.manage