backend_view:
  title: 后台权限
  groups:
    - title: 栏目管理
      slug: channel
      permissions:
        - title: 栏目分类
          slug: channel.manage
        - title: 数据列表
          slug: content.manage
        - title: 内容回收站
          slug: recycle_bin.manage
    - title: 管理员管理
      slug: admin
      permissions:
        - title: 管理员列表
          slug: admin.manage
        - title: 角色列表
          slug: role.manage
        - title: 权限分类
          slug: rule_channel.manage
        - title: 权限列表
          slug: rule.manage
    - title: 系统设置
      slug: setting
      permissions:
        - title: 快捷方式
          slug: quick.manage
        - title: 友情链接
          slug: link.manage
        - title: 站点配置
          slug: setting.manage
backend_api:
  title: 后台接口权限
  groups:
    - title: 栏目管理
      slug: channel
      permissions:
        - title: 栏目分类列表
          slug: channel.index
        - title: 栏目启用/禁用
          slug: channel.status
        - title: 栏目删除
          slug: channel.delete
        - title: 栏目添加
          slug: channel.add
        - title: 栏目编辑
          slug: channel.edit
    - title: 管理员管理
      slug: admin
      permissions:
        - title: 管理员新增
          slug: admin.add
        - title: 管理员编辑
          slug: admin.edit
        - title: 管理员启动/停用
          slug: admin.status
        - title: 管理员删除
          slug: admin.delete
        - title: 管理员批量删除
          slug: admin.delete_batch
        - title: 角色新增
          slug: role.add
        - title: 角色编辑
          slug: role.edit
        - title: 角色启用/停用
          slug: role.status
        - title: 角色删除
          slug: role.delete
        - title: 角色批量删除
          slug: role.delete_batch
    - title: 系统设置
      slug: setting
      permissions:
        - title: 保存配置
          slug: setting.save