backend:
  title: 后台设置
  groups:
    - title: 网站信息
      children:
        - title: 网站名称
          type: text
          name: web_name
          tip: 请输入网站信息

        - title: 网站关键词
          type: text
          name: keywords
          tip: 请输入网站关键词

        - title: 网站描述
          type: textarea
          name: description
          tip: 请输入网站描述

        - title: 电话号码
          type: text
          name: tel
          tip: 请输入电话号码

        - title: QQ
          type: text
          name: qq
          tip: 请输入QQ号码

        - title: 微信二维码
          type: image
          name: wechat_img
          tip: 请上传微信二维码

        - title: 电子邮箱
          type: text
          name: email
          tip: 请输入电子邮箱

        - title: 公司名称
          type: text
          name: corporate_name
          tip: 请输入公司名称

        - title: 公司地址
          type: text
          name: address
          tip: 请输入公司地址

        - title: 版权信息
          type: text
          name: power_by
          tip: 请输入版权信息

        - title: 备案号
          type: text
          name: bei_an
          tip: 请输入备案号

        - title: 电脑版统计代码
          type: textarea
          name: tongji_pc
          tip: 请输入电脑版统计代码

        - title: 手机版统计代码
          type: textarea
          name: tongji_m
          tip: 请输入手机版统计代码

    - title: 系统设置
      children:
        - title: 回收站
          type: radio
          name: recycle_bin
          tip: 是否开启回收站
          options:
            - title: 开启
              value: 1
            - title: 关闭
              value: 0

    - title: 文章设置
      children:
        - title: 自动获取文章缩略图
          type: radio
          name: auto_art_pic
          tip: 是否自动获取文章缩略图
          options:
            - title: 开启
              value: 1
            - title: 关闭
              value: 0

    - title: 留言设置
      children:
        - title: 留言邮件提醒管理员
          type: radio
          name: guestbook_email_notice
          tip: 是否开启回收站
          options:
            - title: 开启
              value: 1
            - title: 关闭
              value: 0
        - title: 管理员邮箱
          type: text
          name: admin_emails
          tip: 请输入管理员邮箱，多个用英文逗号分隔

    - title: 邮件服务器设置
      children:
        - title: smtp服务器
          type: text
          name: smtp_server
          tip: 请输入smtp服务器
        - title: 服务器端口
          type: text
          name: smtp_port
          tip: 请输入服务器端口
        - title: 邮箱账号
          type: text
          name: smtp_user
          tip: 请输入邮箱账号
        - title: 邮箱密码
          type: password
          name: smtp_pass
          tip: 请输入邮箱密码
        - title: 发送人地址
          type: text
          name: smtp_email_from
          tip: 请输入发送人地址