server:
  projectName: "gf_cms"
  backendPrefix: "admin"
  address: ":8002"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  serverRoot: "./resource/public"

database:
  default:
    type: "mysql"
    debug: "true"
    dryRun: 0
    prefix: "cms_"
    removePrefix: "cms_"
    charset: "utf8"
    host: "127.0.0.1"
    port: "3306"
    user: "root"
    pass: ""
    name: "gf_cms"

redis:
  default:
    address: 127.0.0.1:6379
    db: 0

logger:
  level: "all"
  stdout: true

gfcli:
#  build:
#    name: "gfCms"
#    arch: "amd64"
#    system: "linux"
#    mod: "none"
#    cgo: 0
#    pack: "resource/public,resource/template"
#    version: "v1.0.0"
#    extra: ""
  build:
    name: "gfCms"
    arch: "amd64"
    system: "darwin"
    mod: "none"
    cgo: 0
    pack: "resource/public,resource/template"
    version: ""
    extra: ""